archlinux-wallpaper:
  extension: .svg
  output: archlinux-wallpaper
eyes:
  extension: .svg
  output: eyes
hex:
  extension: .svg
  output: hex
lines:
  extension: .svg
  output: lines
palette:
  extension: .svg
  output: palette
sun:
  extension: .svg
  output: sun
ts-code:
  extension: .svg
  output: ts-code
nix-catppuccin:
  extension: .svg
  output: catppuccin
